#!/bin/bash

# {{ Questioning User for IP, Netmask, Nameserver, Default Gateway }}

echo "What IP address would you like to use?"
read IP

echo "What Netmask would you like to use?"
read Netmask

echo "What Nameserver would you like use?"
read Nameserver

echo "What is your Default Gateway?"
read Gateway

# {{ Setting Live Config }}

ifconfig eth1 $IP
ifconfig eth1 netmask $Netmask
#route add default gw $Gateway eth1 

# {{ Appending Resolv.Conf with User's new DNS Server }}

grep -v "$nameserver" /etc/resolv.conf > /tmp/resolv.conf
echo "nameserver" $Nameserver >> /tmp/resolv.conf
cat /tmp/resolv.conf > /etc/resolv.conf
rm -f /tmp/resolv.conf

# {{ Create File }}

#touch /etc/sysconfig/network-scripts/ifcfg-eth1
touch /tmp/ifcfg-eth1

# {{ Creating ifcfg-eth1 }}

  echo "# Generated by dracut initrd"  > /tmp/ifcfg-eth1
  echo 'NAME="eth1"'	     >>		 /tmp/ifcfg-eth1
  echo "ONBOOT=yes" 	     >>		 /tmp/ifcfg-eth1
  echo "NETBOOT=yes"	     >>		 /tmp/ifcfg-eth1
  echo "IPADDR="$IP 	     >>		 /tmp/ifcfg-eth1
  echo "NETMASK="$Netmask    >>		 /tmp/ifcfg-eth1
  echo "IPV6INIT=yes"	     >>		 /tmp/ifcfg-eth1
  echo "BOOTPROTO=none"      >>		 /tmp/ifcfg-eth1
  echo "TYPE=Ethernet"	     >>		 /tmp/ifcfg-eth1
  echo "DNS1="$Nameserver    >>          /tmp/ifcfg-eth1
  echo 'NW_CONTROLLED="no"'  >>		 /tmp/ifcfg-eth1
# echo "Gateway="$Gateway    >>		 /tmp/ifcfg-eth1

# {{ Moving ifcfg-eth1 to network-scripts }}

mv /tmp/ifcfg-eth1 /etc/sysconfig/network-scripts
